# Generated by Django 4.0.6 on 2022-07-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(max_length=120)),
                ('commerce', models.CharField(max_length=120)),
                ('participants', models.CharField(blank=True, max_length=120)),
                ('amount_spent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_refunded', models.BooleanField()),
                ('category', models.CharField(choices=[('OCO', 'Ocio'), ('FOD', 'Comida'), ('DEB', 'Deberes'), ('INV', 'Inversión')], default='FOD', max_length=3)),
            ],
        ),
    ]
