# Generated by Django 4.0.6 on 2022-07-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_refunded',
            field=models.BooleanField(choices=[('Y', 'Yes'), ('N', 'No')]),
        ),
        migrations.AlterField(
            model_name='expense',
            name='participants',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
