# Generated by Django 4.0.6 on 2022-08-01 22:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_alter_expense_is_refunded_alter_expense_participants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(blank=True, default='Select', max_length=10),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_refunded',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='participants',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
