# Generated by Django 4.0.6 on 2022-08-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_expense_date_alter_expense_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='product',
            field=models.CharField(default='N/A', max_length=120),
        ),
    ]
