# Generated by Django 4.0.4 on 2022-08-06 21:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0005_settings_alter_expense_refund_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='end_date',
            field=models.DateField(default=datetime.date(2022, 8, 28)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 8, 1)),
        ),
    ]
