# Generated by Django 4.0.4 on 2022-08-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_alter_expense_is_refunded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='is_refunded',
            field=models.CharField(blank=True, default='N/A', max_length=200, null=True),
        ),
    ]
