# Generated by Django 4.1 on 2022-08-23 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='channel',
            field=models.CharField(blank=True, default='all', max_length=120, null=True),
        ),
    ]
