# Generated by Django 4.1 on 2022-08-23 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_stats_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='stats',
            name='sort',
            field=models.CharField(blank=True, default='ascending', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='stats',
            name='channel',
            field=models.CharField(blank=True, default='all methods', max_length=120, null=True),
        ),
    ]
